version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  print_hello:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run Script1
          command: echo "Hello Guys!!!"

  print_world:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run Script2
          command: echo "Now print World!!!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - print_hello
      - print_world:
          requires: 
            - print_hello
