version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "${CIRCLE_WORKFLOW_ID}"
    steps:
      - run: echo << parameters.to >>

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run Script1
          command: echo "Hello $ENV_NAME!!!, tet to output here" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Output
          command: cat ~/output.txt
  
  output_command:
    steps:
      - print_pipeline_id



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  welcome: 
    jobs:
      - welcome/run
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output
