version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  
  first_job:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: echo "hello world" 

  create_infrastructure: 
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:          
          fingerprints: ["dd:b1:b8:34:a1:73:4b:83:e5:12:35:fa:03:5d:6a:e7"] 
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Run Playbook and Configure server
            command: |
              ansible-playbook -i inventory 

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  welcome: 
    jobs:
      - welcome/run
      - first_job
      - create_infrastructure