version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  print_hello:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run Script1
          command: echo "Hello Guys!!!"

  print_world:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run Script2
          command: echo "Now print World!!!"

workflows:
  version: 2
    jobs:
      - print_hello
      - print_world:
          requires: 
            - print_hello
